# Generated by Django 3.2.3 on 2021-05-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0002_auto_20210529_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
