# Generated by Django 3.2.3 on 2021-05-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0003_auto_20210529_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
