# Generated by Django 3.2.3 on 2021-05-29 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0004_alter_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 16, 6, 3, 102237), null=True),
        ),
    ]
