# Generated by Django 3.2.3 on 2021-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0008_alter_food_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to='food'),
        ),
    ]
