# Generated by Django 3.2.3 on 2021-05-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0009_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, upload_to='customer'),
        ),
    ]
